name: Build Extension Zip

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Yarn Build
        run: yarn run build

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Create ZIP for Extension
        run: |
          cd dist/ext
          zip ../../archivewebpage-ext-${{ steps.package-version.outputs.current-version }}.zip -r ./

      - name: Upload Extension ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: archivewebpage-ext-${{ steps.package-version.outputs.current-version }}.zip
          tag_name: v${{ steps.package-version.outputs.current-version }}
          draft: true
